### ISSUE TITLE
Charging gadget consumes infinite fuel item

### ISSUE THREAD

**Issue by gigili** [Direwolf20-MC/ChargingGadgets#11]
Minecraft version: 1.19.2
Mod version: charginggadgets-1.9.0.jar
Os: Win 10

When using the [ProjectE](https://www.curseforge.com/minecraft/mc-mods/projecte) and [Project Expension](https://www.curseforge.com/minecraft/mc-mods/project-expansion) mods, the Expansion addon adds a new item called `Infinite Fuel`. This item is meant to act like an infinite coal in furnaces and similar machines.

What is happening: 
But when placed inside of the charging gadget it gets consumed after a single use as if a single piece of charcoal was put into it. 

What was expected to happen:
The charging gadget will continue to use the item without consuming it

Could this be considered a bug or just a bad match between mods ?

**Comment by MichaelHillcox** [comment]
I'll look into it when I get a moment :+1:
