### ISSUE TITLE
Can't transfer power to Charger.

### ISSUE THREAD

**Issue by QuirkyLarry** [Direwolf20-MC/ChargingGadgets#4]
I can not transfer power to the charger using the "Pipez" mod. This is the only mod I can find for Minecraft 1.18 that allows me to charge gadgets. It would be nice to be able to add power to the gadget charger via another source. I.E. a nuclear power generator.

**Comment by MichaelHillcox** [comment]
Sorry, right now we don't support exporting power from the charger
