### ISSUE TITLE
Crashing world, MC 1.18.1, Forge 39.0.57

### ISSUE THREAD

**Issue by StrangeThistle** [Direwolf20-MC/ChargingGadgets#5]
Crash report: https://pastebin.com/TFLQHZxX

Since the last round of forge updates (and many mod updates), placing a charging station crashes my game and breaks my world with a ticking world exception. This still happens when Charging Gadgets 1.5.0 is the only mod installed.

**Comment by FuuNoKamiOka** [comment]
Not sure if it's needed but I am also having this same problem.

**Comment by Tomatoe1** [comment]
I'm having the same issue, literally just now as I was playing. I'm not sure what the issue is either.

**Comment by bitberlin** [comment]
I can confirm the same issue. I made a forge update, loaded my world and it crashed:
[crash-2022-01-25_23.43.36-server.txt](https://github.com/Direwolf20-MC/ChargingGadgets/files/7944683/crash-2022-01-25_23.43.36-server.txt)

**Comment by MichaelHillcox** [comment]
Fixed, releasing soon
